### ISSUE TITLE
Question: integer fd vs char * file path in `launchApp`

### ISSUE THREAD

**Issue by jameshcorbett** [common-tools-interface/cti#9]
The [launchApp](https://github.com/common-tools-interface/cti#application-launch) function takes stdout and stderr as integer fds but stdin as a `const char *`. Why is there this difference, and also why are they are not all taken as `const char *` file paths? Is it to support non-file streams? It looks like the [Slurm implementation](https://github.com/common-tools-interface/cti/blob/master/src/frontend/frontend_impl/SLURM/Frontend.cpp#L687) uses `/proc/pid/fd` to convert the fds to file paths.

Just wondering if I'm overlooking something.

Tagging @dongahn.

**Comment by dongahn** [comment]
Tagging @johnlvogt and @ardangelo.

**Comment by ardangelo** [comment]
I'm not sure why the original CTI interface specified a file input instead of a file descriptor, but there's currently no technical reason why it is a file instead of a descriptor. Internally, in all implementations, the input file path is opened as a descriptor.

**Comment by ardangelo** [comment]
We have just opened a task to add an additional launch function that takes a file descriptor for input instead of a file.

**Comment by jameshcorbett** [comment]
Thanks for the explanation. I don't know if it's worth adding a new function---up to you of course.
